### ISSUE TITLE
Extracting full list of clusters

### ISSUE THREAD

**Issue by browshanravan** [JinmiaoChenLab/Rphenograph#11]
In your `iris` example, when you execute `membership(Rphenograph_out[[2]])` you get a list of flower indices (1-149) and their associated Rphenograph cluster they belong to as shown below.

![Screen Shot 2020-05-11 at 22 35 44](https://user-images.githubusercontent.com/5493052/81614332-d0e2d600-93d7-11ea-88a2-f6a743608a52.png)

Do you know how I can extract the list of clusters, as shown individually, in the correct order? so I want something like `111111..22222..23123.... etc`

**Comment by SamGG** [comment]
I don't see what you want to do. Look at order or rank functions.

**Comment by browshanravan** [comment]
@SamGG I don't want to order them or rank them. I want to extract the cluster values as they appear. Basically I want all the 149 cluster values without the `1,2,3,4,5 ..149` values at the top of each cluster value.

**Comment by SamGG** [comment]
```
xyz = Rphenograph::Rphenograph(iris[,-5])
as.numeric(membership(xyz[[2]]))
```
Best.

**Comment by SamGG** [comment]
In fact, this is only a view. It's because each numerical values has a name.
```
> unname(membership(xyz[[2]]))  # remove name
  [1] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 3 2 3 2 3 2 3 3 3 3
 [64] 2 3 2 3 3 2 3 2 3 2 2 2 2 2 2 2 3 3 3 3 2 3 2 2 3 3 3 3 2 3 3 3 3 3 3 3 3 4 2 4 4 4 4 3 4 4 4 4 4 4 2 2 4 4 4 4 2 4 2 4 2 4 4
[127] 2 2 4 4 4 4 4 2 2 4 4 4 2 4 4 4 2 4 4 4 2 4 4 2

> str(membership(xyz[[2]]))  # view the structure
 'membership' Named num [1:150] 1 1 1 1 1 1 1 1 1 1 ...
 - attr(*, "names")= chr [1:150] "1" "2" "3" "4" ...
```
HTH

**Comment by browshanravan** [comment]
@SamGG it worked! Thank you so much! Really appreciate your time!

**Comment by SamGG** [comment]
No problem. This is the way to improve our skills.
Let me know if you are struggling with computational time.
