### ISSUE TITLE
Rphenograph doesn't recognize my clean dataset

### ISSUE THREAD

**Issue by zoqaiyum** [JinmiaoChenLab/Rphenograph#19]
Hi, 

I have removed all NAs from my dataframe and I am trying to run Rphenograph. 

I checked the number of missing values in my dataset to ensure it is complete, and the answer to the code below is 0. 

`sum(is.na(mydata))`

I also checked to see if my dataset had any characters, and the answer to the code below was 0. 

`sum(is.character(mydata))`

Now, I am running my Rphenograph (code below). 

`set.seed(436)`
`Rphenograph_out <- Rphenograph(mydata, k = 45)`

However, I am getting this error: 

Run Rphenograph starts:
  -Input data of 40178 rows and 10 columns
  -k is set to 45
  Finding nearest neighbors...Warning: NAs introduced by coercionWarning: NAs introduced by coercionError in nn2(data, data, k, searchtype = "standard") : 
  NA/NaN/Inf in foreign function call (arg 1)

How would I fix this? It appears Rphenograph has trouble recognizing that my dataset does not have NAs. 

Thanks in advance!

**Comment by SamGG** [comment]
Hi,
Did you also check `sum(is.infinite(mydata))` and `sum(is.nan(mydata))` and `sum(is.finite(mydata))` ?
Samuel

**Comment by zoqaiyum** [comment]
Hi @SamGG 

I ran the above codes and this is the error that pops up: 

Error in is.infinite(mydata) : 
  default method not implemented for type 'list'

Error in is.nan(mydata) : 
  default method not implemented for type 'list'

Error in is.finite(mydata) : 
  default method not implemented for type 'list'

My dataset is a dataframe so I am unsure why it is being recognized type "list".

**Comment by SamGG** [comment]
As stated in the help and example of Rphenograph, the input data must be a matrix of numerical values.
#' iris_unique <- unique(iris) # Remove duplicates
#' data <- as.matrix(iris_unique[,1:4])
#' Rphenograph_out <- Rphenograph(data, k = 45)
```
mydata2 <- as.matrix(mydata)
is.numeric(mydata2)
```
If mydata2 is numeric, and has no Inf/NA/NaN, Rphenograph should work.
Best

**Comment by zoqaiyum** [comment]
Hi @SamGG 

My dataset is actually from an RNA sequencing project. A screenshot of my data is below: 

![IMG_6240](https://github.com/JinmiaoChenLab/Rphenograph/assets/119648999/2d088cb4-d417-4bdd-9ab2-eaf0d892731e)

As you can see, there is a column named "orig_barcodes" which is as a result of our cells being barcoded for sequencing. 

So after removing all missing values from this dataset, I proceeded to change all character columns (including the orig_barcode column) into factor columns using this code below: 
`mydata<- mydata %>% mutate_if(is.character, as.factor) `

Next, I changed my dataframe into a matrix as you suggested: 
`mydata <- as.matrix(mydata)`

Changing the dataframe into a matrix resulted in the orig_barcode column becoming a character column again. The other column, sample_id, can be renamed into anything I choose so I can make it numeric, however the orig_barcode column is difficult to change to numeric. Any suggestions on how I can proceed?

Thanks.

**Comment by SamGG** [comment]
The data should be organized as the iris dataset,
ie rows = cells, columns = genes, the matrix containing the count of gene in the corresponding cell,
that is, the same format than Rtsne.
You should probably compute a PCA in order to keep the 50 first principal components, in typical scRNAseq.
That being said, I never worked on scRNAseq, nor Seurat or monocle. If you want to do it on yourself, that's great but you should also look at https://bioconductor.org/books/release/OSCA/
Best.

**Comment by zoqaiyum** [comment]
Thanks @SamGG
