### ISSUE TITLE
Changing clustering resolution

### ISSUE THREAD

**Issue by asmagen** [JinmiaoChenLab/Rphenograph#2]
Hello

I'm currently changing the clustering resolution (increasing or decreasing the number of output clusters) by changing the KNN parameter.
Is there a way to change the resolution by changing the Louvain parameters and not the KNN?

Thanks

**Comment by SamGG** [comment]
Hi,
There seems to be no such parameter in the Louvain implementation available in the igraph package.
https://igraph.org/r/doc/cluster_louvain.html

**Comment by SamGG** [comment]
Hi,
jmlong has implemented the resolution parameter in the Louvain algorithm in igraph (C code) and rigraph (R functions depending on C).
https://github.com/igraph/rigraph/issues/239#issuecomment-637152537
Changing the k does not properly achieve this feature IMHO.
If you are still using Rphenograph, have a look at my current fork.
https://github.com/i-cyto/Rphenograph
Best.
