### ISSUE TITLE
Unclustered data

### ISSUE THREAD

**Issue by anirudhpatir** [JinmiaoChenLab/Rphenograph#3]
Hi,

Have enjoyed using your package, just had an issue with cases where samples remain unclustered.

On using lower values of k, some data remains unclustered. Is it possible to add these to the output membership (unconnected components of the graph), as currently these are removed from the final output and it's difficult to retrace which samples these are.

Thank you

**Comment by funa1019** [comment]
hi I have the same problem.....so sad

**Comment by SamGG** [comment]
Hi,
I am not the developer, but a frequent user.
I never came to such a problem, but I didn't check the output it in fact. I am curious about how some samples are not reported. If you could share your dataset or a toy example, that would be nice.
Those samples could be identified using `setdiff` function I think. Try something like:
```
unclustered_ids = setdiff(seq(nrow(my_dataset)), as.numeric(names(membership(my_rphenograph_result[[2]]))))
```
Let me know.
